### PR TITLE
enhancement: Handle optional `retries` arg passed to Cerbos clients

### LINKED ISSUE #9: Add automatic retries
Add ability to automatically retry operations based on user-provided configuration

### PR DESCRIPTION
**Pull request by Sambigeara**
Fixes #9 

Also fixes two `test_plan_resources` tests.

### CODE REVIEW

**Review by charithe — APPROVED** [review]
Brilliant! 

Does httpx have request retries? If not, could we add those as well? (In a different PR.)

**Comment by Sambigeara** [comment]
Gosh, that was a bit lazy of me. I'll merge this and handle request retries separately.

**Comment by Sambigeara** [comment]
For some reason, I can't merge this PR because it's complaining of unsigned commits (even though all are signed 🤷‍♂️ ). So I'm going to rebase-squash the above into a single commit and do the request retries in this PR regardless. Hopefully that'll unclog it for next review.

**Comment by Sambigeara** [comment]
All later changes are within the [second commit](https://github.com/cerbos/cerbos-sdk-python/pull/19/commits/e1275052adaf204e670968bd4195a91086008c6a)

**Review by charithe — APPROVED** [review]
LGTM 👍🏽

**Review by charithe — COMMENTED** [review]
Let's exclude the `cerbos/sdk/__pycache__` directory from the commit. I think it got included because the `.gitignore` entry I added is wrong.

**Comment by Sambigeara** [comment]
I think the `.gitignore` is correct, I'm not sure how those snuck through 🤔 . I'll `git rm --cached` and see what happens

**Review by charithe — APPROVED** [review]

**Pull request merged**
