### PR TITLE
feat: Add support for `exportVariables` policies

### LINKED ISSUE #33: Support `exportVariables` policies in Admin API
https://github.com/cerbos/cerbos/pull/1646

### PR DESCRIPTION
**Pull request by Sambigeara**
closes #33

### CODE REVIEW

**Comment by Sambigeara** [comment]
Just adding a test case or two

**Comment by charithe** [comment]
Oh cool! Thanks. I'll close #34 in favour of this.

**Comment by Sambigeara** [comment]
Ooooh dear. In my haste I completely missed your PR, sorry @charithe 🤦‍♂️

**Comment by charithe** [comment]
No problem at all. I was struggling to make the checks pass anyway 😄 

There might be a tiny bug in the unasync script that you might want to incorporate into this: https://github.com/cerbos/cerbos-sdk-python/pull/34/files#diff-e50c62e4f5ee84321809474534eab11557232a90e77f4f5abc428d1ffcf58292. On Linux, the temp file has to be closed to flush all the contents out or it ends up losing some content.

**Comment by Sambigeara** [comment]
I saw that, thanks for flagging, I'll add it in

**Pull request merged**
